"""Headless five-round ant adaptation prototype."""

from .engine import GameEngine, InvalidDecision, PROBLEM_IDS
from .models import (
    ActionCommand,
    ActionOption,
    CardInstance,
    CardRole,
    ColumnState,
    DisasterCard,
    EnvironmentCard,
    GameState,
    OptimizationRequirement,
    ProblemRollRule,
    PlayedCard,
    RoundContext,
    RoundDecision,
    RoundPhase,
    RoundRecord,
    ShieldSpec,
    Size,
    SizeEffectSpec,
    TraitCard,
)

__all__ = [
    "ActionCommand",
    "ActionOption",
    "CardInstance",
    "CardRole",
    "ColumnState",
    "DisasterCard",
    "EnvironmentCard",
    "GameEngine",
    "GameState",
    "InvalidDecision",
    "PROBLEM_IDS",
    "OptimizationRequirement",
    "ProblemRollRule",
    "PlayedCard",
    "RoundContext",
    "RoundDecision",
    "RoundPhase",
    "RoundRecord",
    "ShieldSpec",
    "Size",
    "SizeEffectSpec",
    "TraitCard",
]
