let gameId = null;
let state = null;
let retained = new Set();
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));

async function api(path, data = null) {
  const options = data ? {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(data)} : {};
  const response = await fetch(path, options);
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "通信に失敗しました。");
  return result;
}
function notice(message, error = false) { const box = $("#notice"); box.textContent = message || ""; box.className = message ? (error ? "error" : "message") : ""; }
function tagHTML(tag, count = null) { const value = count ?? tag.count; return `<span class="tag" style="--tag-color:${esc(tag.color)}"><svg aria-hidden="true"><use href="#symbol-${esc(tag.symbol)}"></use></svg>${esc(tag.name)}${value != null ? ` ${value}` : ""}</span>`; }
function requirementsHTML(items, progress = false) {
  if (!items.length) return "<span>条件なし</span>";
  return items.map((item) => { const numbers = progress && item.actual != null ? `${item.actual}/${item.required}` : item.required; return `<span class="requirement ${item.missing > 0 ? "missing" : ""}">${tagHTML(item)} ×${numbers}${item.missing > 0 ? `（あと${item.missing}）` : ""}</span>`; }).join(" ");
}
function effectHTML(effect) {
  if (!effect) return "";
  const parts = [];
  if (effect.text) parts.push(esc(effect.text));
  if (effect.prosperity) parts.push(`繁栄 +${effect.prosperity}`);
  if (effect.draw_cards) parts.push(`カードを${effect.draw_cards}枚ドロー`);
  effect.shields.forEach((shield) => parts.push(`${esc(shield.name)}シールド +${shield.amount}`));
  return parts.map((part) => `<span class="effect">${part}</span>`).join(" ") || "<span class='effect'>効果なし</span>";
}
function cardBand(tags) { if (!tags.length) return "#777"; const stop = 100 / tags.length; return `linear-gradient(90deg,${tags.flatMap((tag, i) => [`${tag.color} ${i * stop}%`, `${tag.color} ${(i + 1) * stop}%`]).join(",")})`; }
function cardHTML(card, selectable = false) { return `<article class="card" style="--tag-band:${cardBand(card.tags)}" ${selectable ? `data-keep="${esc(card.id)}" tabindex="0" role="button"` : ""}><div class="meta">${esc(card.role)}</div><h3>${esc(card.name)}</h3><p>${esc(card.text)}</p><div class="self-tags"><span class="label">カードのタグ</span><div class="tag-row">${card.tags.map((tag) => tagHTML(tag)).join("") || "条件なし"}</div></div><div class="required-tags condition"><span class="label">起動条件</span>${requirementsHTML(card.requirements)}</div><div class="effect-row">${card.options.map(effectHTML).join("") || "<span class='effect'>起動効果なし</span>"}</div></article>`; }

$("#start").addEventListener("click", async () => { try { const result = await api("/api/new", {seed:Number($("#seed").value || 0)}); gameId = result.game_id; state = result.state; $("#setup").classList.add("hidden"); $("#game").classList.remove("hidden"); $("#restart").classList.remove("hidden"); notice("ゲームを開始しました。まずサイズを選んでください。"); render(); } catch (error) { notice(error.message, true); } });
$("#restart").addEventListener("click", () => { gameId = null; state = null; retained.clear(); $("#game").classList.add("hidden"); $("#setup").classList.remove("hidden"); $("#restart").classList.add("hidden"); });
async function act(kind, extra = {}) { try { const result = await api("/api/action", {game_id:gameId, kind, ...extra}); state = result.state; retained.clear(); render(); } catch (error) { notice(error.message, true); } }
function render() { renderForecast(); renderOverview(); renderDecision(); renderBoard(); }
function renderForecast() { $("#forecast").innerHTML = `<h2>公開された5ラウンドの環境変化予報</h2><div class="forecast-grid">${state.forecast.map((environment) => `<article class="forecast-card ${environment.current ? "current" : ""} ${environment.completed ? "completed" : ""}"><div class="meta">ラウンド ${environment.round}${environment.current ? "・現在" : ""}</div><h3>${esc(environment.name)}</h3><p>${esc(environment.text)}</p><div class="optimization"><strong>最適化：${esc(environment.optimization.name)}</strong><div>${requirementsHTML(environment.optimization.requirements)}</div></div></article>`).join("")}</div>`; }
function problemsHTML(problems, resolved = false) { return problems.map((problem) => `<article class="problem"><strong>${esc(problem.name)}</strong><span>1d6: <b>${problem.roll ?? "?"}</b></span><span>シールド: ${problem.defense ?? problem.shield ?? 0}</span><span>未防御: ${problem.unblocked ?? "?"}</span>${problem.penalty != null ? `<span class="${problem.penalty ? "warning" : "success"}">指数減点: ${problem.penalty}</span>` : ""}</article>`).join(""); }
function resultHTML(result) { if (!result) return ""; return `<div class="result"><strong>ラウンド ${result.round}「${esc(result.environment_name)}」の結果</strong><div class="result-steps"><div>開始 ${result.score_before} → 繁栄後 ${result.score_after_prosperity}（基礎 ${result.prosperity_base} × サイズ ${result.size_multiplier}）</div><div class="problem-grid">${problemsHTML(result.problems, true)}</div><div>問題による減点: ${result.problem_penalty} → ${result.score_after_problems}</div><div class="${result.optimization_met ? "success" : "warning"}">最適化: ${esc(result.optimization_name)}（${result.optimization_met ? "達成" : `未達・${result.optimization_half_loss}点減` }）</div><div><strong>最終繁栄: ${result.total_prosperity}</strong></div></div></div>`; }
function renderOverview() { const environment = state.environment; $("#overview").innerHTML = `${resultHTML(state.last_result)}<h2>ラウンド ${state.round}/5・${esc(environment.name)}</h2><p>${esc(environment.text)}</p><div class="stats"><div class="stat">繁栄<strong>${state.prosperity}</strong></div><div class="stat">サイズ<strong>${esc(state.size_name)}</strong></div><div class="stat">今ラウンドの基礎<strong>${state.round_prosperity_base}</strong></div><div class="stat">手札<strong>${state.hand.length}/${state.hand_limit}</strong></div></div><h3>毎ラウンド独立の3問題（各1d6）</h3><div class="problem-grid">${problemsHTML(state.problems)}</div><div class="optimization"><strong>今ラウンドの最適化：${esc(environment.optimization.name)}</strong><div>${requirementsHTML(environment.optimization.requirements, true)}</div><span class="${environment.optimization.met ? "success" : "warning"}">${environment.optimization.met ? "達成" : "未達"}</span></div>`; }
function renderDecision() { const box = $("#decision"); if (state.finished) { box.innerHTML = `<h2>5ラウンド終了</h2><p>最終繁栄 <strong>${state.prosperity}</strong></p><button class="primary" onclick="$(\"#restart\").click()">もう一度遊ぶ</button>`; return; } if (state.phase === "size") { box.innerHTML = `<h2>1. サイズを選ぶ</h2><p class="phase-help">大きいほど繁栄は増えますが、保持できるカードは減ります。</p><div class="button-row">${state.legal_sizes.map((size) => `<button onclick="act('size',{size:'${size.id}'})"><strong>${esc(size.name)}</strong><br>繁栄 ×${size.multiplier}・保持 ${size.retention}枚</button>`).join("")}</div>`; } else if (state.phase === "retain") { box.innerHTML = `<h2>2. 公開カードを保持 <span id="keep-count">0/${state.retention_limit}</span></h2><p class="phase-help">カードを選び、保持上限まで手札に加えます。</p><div class="cards">${state.candidates.map((card) => cardHTML(card, true)).join("")}</div><div class="button-row"><button class="primary" id="keep-button">保持して進む</button></div>`; document.querySelectorAll("[data-keep]").forEach((element) => { element.addEventListener("click", () => toggleKeep(element.dataset.keep)); element.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); toggleKeep(element.dataset.keep); } }); }); $("#keep-button").addEventListener("click", () => act("retain", {card_ids:[...retained]})); } else { box.innerHTML = `<h2>3. 配置・起動</h2><p class="phase-help">手札のカードを進化列へ配置し、条件を満たす列の最上段を起動します。</p><h3>手札</h3>${state.hand.length ? `<div class="cards">${state.hand.map(handCardHTML).join("")}</div>` : "<p>手札はありません。</p>"}<div class="button-row"><button class="primary danger" onclick="act('resolve')">このラウンドを解決</button></div>`; } }
function toggleKeep(id) { if (retained.has(id)) retained.delete(id); else if (retained.size < state.retention_limit) retained.add(id); else { notice(`保持できるのは${state.retention_limit}枚までです。`, true); return; } document.querySelectorAll("[data-keep]").forEach((element) => element.classList.toggle("selected", retained.has(element.dataset.keep))); $("#keep-count").textContent = `${retained.size}/${state.retention_limit}`; }
function handCardHTML(card) { const actions = state.columns.map((column) => `<button onclick="act('play',{card_id:'${esc(card.id)}',column:${column.index}})">列${column.index + 1}へ配置</button><button onclick="act('support',{card_id:'${esc(card.id)}',column:${column.index}})">列${column.index + 1}の支援</button>`).join(""); return cardHTML(card).replace("</article>", `<div class="hand-actions">${actions}</div></article>`); }
function renderBoard() { $("#board").innerHTML = `<h2>進化列</h2><p class="phase-help">列のタグは最適化、最上段を除くタグは起動条件に使います。</p><div class="columns">${state.columns.map(columnHTML).join("")}</div>`; }
function columnHTML(column) { const cards = column.cards.map((card) => `<div class="stack-card ${card.top ? "top" : ""} ${card.support ? "support" : ""}"><strong>${esc(card.name)}</strong><br><small>${card.top ? "最上段" : card.support ? "支援" : "下段"}${card.activated ? "・起動済み" : ""}</small><div class="tag-row">${card.tags.map((tag) => tagHTML(tag)).join("")}</div></div>`).join(""); const activations = column.activations.map((activation) => `<div><button ${activation.enabled ? "" : "disabled"} title="${esc(activation.reason)}" onclick="act('activate',{column:${column.index},option:${activation.option}})">起動：${effectHTML(activation.effect)}</button>${activation.requirements.length ? `<div class="condition">条件：${requirementsHTML(activation.requirements, true)}</div>` : ""}</div>`).join(""); return `<article class="column"><h3>${esc(column.name)} <small>${column.cards.length}/${column.capacity}</small></h3><span class="label">列の全タグ（最適化）</span><div class="tag-row">${column.tags.map((tag) => tagHTML(tag)).join("") || "なし"}</div><span class="label">起動に使うタグ</span><div class="tag-row">${column.activation_tags.map((tag) => tagHTML(tag)).join("") || "なし"}</div><div class="stack">${cards || "空"}</div>${column.next_pushed ? `<p class="warning">次に押し出されるカード：${esc(column.next_pushed)}</p>` : ""}<div class="button-row">${activations}</div></article>`; }
